services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: rachit4018
      POSTGRES_PASSWORD: portal
      POSTGRES_DB: portal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rachit4018 -d portal"]
      interval: 2s
      retries: 20
      timeout: 3s
    ports:
      - "5432:5432"
    
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://rachit4018:portal@db:5432/portal
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code

volumes:
  db_data:

  
